version: '3.8'

services:
  # backend:
  #   container_name: server
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./server:/app
  #   command: ["npm", "run", "dev"]
  #   environment:
  #     - NODE_ENV=development
  #     - RABBITMQ_URL=amqp://rabbitmq
  #   depends_on:
  #     - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      # for management UI
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password

volumes:
  rabbitmq_data: