

export enum PageAccessPermissionEnum {
    ORGANIZATION_SETTINGS = 1,
    ACCOUNT_MANAGEMENT = 2,
    ROLE_MANAGEMENT = 3,
    POS = 4,
    OUTLET_MANAGEMENT = 5,
    TABLE_MANAGEMENT = 6,
    GRATUITY_MANAGEMENT = 7,
    SALES_TYPE_MANAGEMENT = 8,
}

export enum PermissionEnum {
    SUPER_PERMISSION = 1,
    ORGANIZATION_MANAGEMENT = 2,
    ACCOUNT_MANAGEMENT = 3,
    ROLE_MANAGEMENT = 4,
    OUTLET_MANAGEMENT = 5,
    TABLE_MANAGEMENT = 6,
    GRATUITY_MANAGEMENT = 7,
    SALES_TYPE_MANAGEMENT = 8,
}
